version: '3'

networks:
  default: {}

services:
  redis:
    container_name: redis
    image: redis:3.2
    ports:
      - 6380:6379

  # The Database
  database:
    container_name: database
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

  web:
    container_name: web
    build:
      context: ./docker/web
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
      - ./docker/web/logs:/var/log/httpd
    ports:
      - 9090:80
    depends_on:
      - database
      - redis
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=demo
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
      - SESSION_DRIVER=redis
    env_file: .env

volumes:
  dbdata:
