version: '3'
services:

  # The Application
  app:
    # container_name: laravel-demo-app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
      - redis
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=demo
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
    env_file: .env

  # The Web Server
  web:
    # container_name: laravel_demo_web
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    depends_on:
      - app
    volumes:
      - ./:/var/www/html
    ports:
      - 9090:80

  # The Database
  database:
    container_name: docker_db
    image: mysql:5.7
    volumes:
      - jkdbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3307:3306
    env_file: .env

  # redis
  redis:
    # container_name: docker_redis
    image: redis:4.0-alpine
    ports:
      - 6380:6379
    volumes:
      - jkredisdata:/data

  composer:
    image: composer/composer
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: ["install --ignore-platform-reqs", "dump-autoload --optimize"]

volumes:
  jkdbdata:
  jkredisdata:
